version: '3'
services:
  redis:
    image: 'redis:latest'
  flask:
    build:
      dockerfile: Dockerfile
      context: ./flask
  staticcontent:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./staticContent
    ports:
      - '3000:81'
  proxyserver:
    restart: always
    build:
        dockerfile: Dockerfile
        context: ./ProxyServer
    ports:
      - '3050:80'